services:
  db:
    image: postgres:18
    container_name: duck_analytics_db
    ports:
      - "5671:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: duck_analytics_db
    volumes:
      - duck_analytics_data:/var/lib/postgresql/data

volumes:
  duck_analytics_data:
