/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedCodeRouteImport } from './routes/embed/$code'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedQuestionsIndexRouteImport } from './routes/_authenticated/questions/index'
import { Route as AuthenticatedQueriesIndexRouteImport } from './routes/_authenticated/queries/index'
import { Route as AuthenticatedLogsIndexRouteImport } from './routes/_authenticated/logs/index'
import { Route as AuthenticatedDataSourcesIndexRouteImport } from './routes/_authenticated/data-sources/index'
import { Route as AuthenticatedDashboardsIndexRouteImport } from './routes/_authenticated/dashboards/index'
import { Route as AuthenticatedComponentsIndexRouteImport } from './routes/_authenticated/components/index'
import { Route as AuthenticatedCollectionIndexRouteImport } from './routes/_authenticated/collection/index'
import { Route as AuthenticatedQuestionsNewRouteImport } from './routes/_authenticated/questions/new'
import { Route as AuthenticatedQuestionsIdRouteImport } from './routes/_authenticated/questions/$id'
import { Route as AuthenticatedQueriesNewRouteImport } from './routes/_authenticated/queries/new'
import { Route as AuthenticatedQueriesIdRouteImport } from './routes/_authenticated/queries/$id'
import { Route as AuthenticatedDataSourcesNewRouteImport } from './routes/_authenticated/data-sources/new'
import { Route as AuthenticatedDataSourcesIdRouteImport } from './routes/_authenticated/data-sources/$id'
import { Route as AuthenticatedDashboardsNewRouteImport } from './routes/_authenticated/dashboards/new'
import { Route as AuthenticatedComponentsNewRouteImport } from './routes/_authenticated/components/new'
import { Route as AuthenticatedComponentsIdRouteImport } from './routes/_authenticated/components/$id'
import { Route as AuthenticatedCollectionFolderIdRouteImport } from './routes/_authenticated/collection/$folderId'
import { Route as AuthenticatedDashboardsIdIndexRouteImport } from './routes/_authenticated/dashboards/$id/index'
import { Route as AuthenticatedDashboardsIdEditRouteImport } from './routes/_authenticated/dashboards/$id/edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedCodeRoute = EmbedCodeRouteImport.update({
  id: '/embed/$code',
  path: '/embed/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuestionsIndexRoute =
  AuthenticatedQuestionsIndexRouteImport.update({
    id: '/questions/',
    path: '/questions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQueriesIndexRoute =
  AuthenticatedQueriesIndexRouteImport.update({
    id: '/queries/',
    path: '/queries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogsIndexRoute = AuthenticatedLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDataSourcesIndexRoute =
  AuthenticatedDataSourcesIndexRouteImport.update({
    id: '/data-sources/',
    path: '/data-sources/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardsIndexRoute =
  AuthenticatedDashboardsIndexRouteImport.update({
    id: '/dashboards/',
    path: '/dashboards/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComponentsIndexRoute =
  AuthenticatedComponentsIndexRouteImport.update({
    id: '/components/',
    path: '/components/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionIndexRoute =
  AuthenticatedCollectionIndexRouteImport.update({
    id: '/collection/',
    path: '/collection/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuestionsNewRoute =
  AuthenticatedQuestionsNewRouteImport.update({
    id: '/questions/new',
    path: '/questions/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuestionsIdRoute =
  AuthenticatedQuestionsIdRouteImport.update({
    id: '/questions/$id',
    path: '/questions/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQueriesNewRoute = AuthenticatedQueriesNewRouteImport.update({
  id: '/queries/new',
  path: '/queries/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQueriesIdRoute = AuthenticatedQueriesIdRouteImport.update({
  id: '/queries/$id',
  path: '/queries/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDataSourcesNewRoute =
  AuthenticatedDataSourcesNewRouteImport.update({
    id: '/data-sources/new',
    path: '/data-sources/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataSourcesIdRoute =
  AuthenticatedDataSourcesIdRouteImport.update({
    id: '/data-sources/$id',
    path: '/data-sources/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardsNewRoute =
  AuthenticatedDashboardsNewRouteImport.update({
    id: '/dashboards/new',
    path: '/dashboards/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComponentsNewRoute =
  AuthenticatedComponentsNewRouteImport.update({
    id: '/components/new',
    path: '/components/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComponentsIdRoute =
  AuthenticatedComponentsIdRouteImport.update({
    id: '/components/$id',
    path: '/components/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionFolderIdRoute =
  AuthenticatedCollectionFolderIdRouteImport.update({
    id: '/collection/$folderId',
    path: '/collection/$folderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardsIdIndexRoute =
  AuthenticatedDashboardsIdIndexRouteImport.update({
    id: '/dashboards/$id/',
    path: '/dashboards/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardsIdEditRoute =
  AuthenticatedDashboardsIdEditRouteImport.update({
    id: '/dashboards/$id/edit',
    path: '/dashboards/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/embed/$code': typeof EmbedCodeRoute
  '/collection/$folderId': typeof AuthenticatedCollectionFolderIdRoute
  '/components/$id': typeof AuthenticatedComponentsIdRoute
  '/components/new': typeof AuthenticatedComponentsNewRoute
  '/dashboards/new': typeof AuthenticatedDashboardsNewRoute
  '/data-sources/$id': typeof AuthenticatedDataSourcesIdRoute
  '/data-sources/new': typeof AuthenticatedDataSourcesNewRoute
  '/queries/$id': typeof AuthenticatedQueriesIdRoute
  '/queries/new': typeof AuthenticatedQueriesNewRoute
  '/questions/$id': typeof AuthenticatedQuestionsIdRoute
  '/questions/new': typeof AuthenticatedQuestionsNewRoute
  '/collection/': typeof AuthenticatedCollectionIndexRoute
  '/components/': typeof AuthenticatedComponentsIndexRoute
  '/dashboards/': typeof AuthenticatedDashboardsIndexRoute
  '/data-sources/': typeof AuthenticatedDataSourcesIndexRoute
  '/logs/': typeof AuthenticatedLogsIndexRoute
  '/queries/': typeof AuthenticatedQueriesIndexRoute
  '/questions/': typeof AuthenticatedQuestionsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/dashboards/$id/edit': typeof AuthenticatedDashboardsIdEditRoute
  '/dashboards/$id/': typeof AuthenticatedDashboardsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/embed/$code': typeof EmbedCodeRoute
  '/collection/$folderId': typeof AuthenticatedCollectionFolderIdRoute
  '/components/$id': typeof AuthenticatedComponentsIdRoute
  '/components/new': typeof AuthenticatedComponentsNewRoute
  '/dashboards/new': typeof AuthenticatedDashboardsNewRoute
  '/data-sources/$id': typeof AuthenticatedDataSourcesIdRoute
  '/data-sources/new': typeof AuthenticatedDataSourcesNewRoute
  '/queries/$id': typeof AuthenticatedQueriesIdRoute
  '/queries/new': typeof AuthenticatedQueriesNewRoute
  '/questions/$id': typeof AuthenticatedQuestionsIdRoute
  '/questions/new': typeof AuthenticatedQuestionsNewRoute
  '/collection': typeof AuthenticatedCollectionIndexRoute
  '/components': typeof AuthenticatedComponentsIndexRoute
  '/dashboards': typeof AuthenticatedDashboardsIndexRoute
  '/data-sources': typeof AuthenticatedDataSourcesIndexRoute
  '/logs': typeof AuthenticatedLogsIndexRoute
  '/queries': typeof AuthenticatedQueriesIndexRoute
  '/questions': typeof AuthenticatedQuestionsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/dashboards/$id/edit': typeof AuthenticatedDashboardsIdEditRoute
  '/dashboards/$id': typeof AuthenticatedDashboardsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/embed/$code': typeof EmbedCodeRoute
  '/_authenticated/collection/$folderId': typeof AuthenticatedCollectionFolderIdRoute
  '/_authenticated/components/$id': typeof AuthenticatedComponentsIdRoute
  '/_authenticated/components/new': typeof AuthenticatedComponentsNewRoute
  '/_authenticated/dashboards/new': typeof AuthenticatedDashboardsNewRoute
  '/_authenticated/data-sources/$id': typeof AuthenticatedDataSourcesIdRoute
  '/_authenticated/data-sources/new': typeof AuthenticatedDataSourcesNewRoute
  '/_authenticated/queries/$id': typeof AuthenticatedQueriesIdRoute
  '/_authenticated/queries/new': typeof AuthenticatedQueriesNewRoute
  '/_authenticated/questions/$id': typeof AuthenticatedQuestionsIdRoute
  '/_authenticated/questions/new': typeof AuthenticatedQuestionsNewRoute
  '/_authenticated/collection/': typeof AuthenticatedCollectionIndexRoute
  '/_authenticated/components/': typeof AuthenticatedComponentsIndexRoute
  '/_authenticated/dashboards/': typeof AuthenticatedDashboardsIndexRoute
  '/_authenticated/data-sources/': typeof AuthenticatedDataSourcesIndexRoute
  '/_authenticated/logs/': typeof AuthenticatedLogsIndexRoute
  '/_authenticated/queries/': typeof AuthenticatedQueriesIndexRoute
  '/_authenticated/questions/': typeof AuthenticatedQuestionsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/dashboards/$id/edit': typeof AuthenticatedDashboardsIdEditRoute
  '/_authenticated/dashboards/$id/': typeof AuthenticatedDashboardsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/embed/$code'
    | '/collection/$folderId'
    | '/components/$id'
    | '/components/new'
    | '/dashboards/new'
    | '/data-sources/$id'
    | '/data-sources/new'
    | '/queries/$id'
    | '/queries/new'
    | '/questions/$id'
    | '/questions/new'
    | '/collection/'
    | '/components/'
    | '/dashboards/'
    | '/data-sources/'
    | '/logs/'
    | '/queries/'
    | '/questions/'
    | '/settings/'
    | '/dashboards/$id/edit'
    | '/dashboards/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/embed/$code'
    | '/collection/$folderId'
    | '/components/$id'
    | '/components/new'
    | '/dashboards/new'
    | '/data-sources/$id'
    | '/data-sources/new'
    | '/queries/$id'
    | '/queries/new'
    | '/questions/$id'
    | '/questions/new'
    | '/collection'
    | '/components'
    | '/dashboards'
    | '/data-sources'
    | '/logs'
    | '/queries'
    | '/questions'
    | '/settings'
    | '/dashboards/$id/edit'
    | '/dashboards/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/sign-up'
    | '/embed/$code'
    | '/_authenticated/collection/$folderId'
    | '/_authenticated/components/$id'
    | '/_authenticated/components/new'
    | '/_authenticated/dashboards/new'
    | '/_authenticated/data-sources/$id'
    | '/_authenticated/data-sources/new'
    | '/_authenticated/queries/$id'
    | '/_authenticated/queries/new'
    | '/_authenticated/questions/$id'
    | '/_authenticated/questions/new'
    | '/_authenticated/collection/'
    | '/_authenticated/components/'
    | '/_authenticated/dashboards/'
    | '/_authenticated/data-sources/'
    | '/_authenticated/logs/'
    | '/_authenticated/queries/'
    | '/_authenticated/questions/'
    | '/_authenticated/settings/'
    | '/_authenticated/dashboards/$id/edit'
    | '/_authenticated/dashboards/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  EmbedCodeRoute: typeof EmbedCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$code': {
      id: '/embed/$code'
      path: '/embed/$code'
      fullPath: '/embed/$code'
      preLoaderRoute: typeof EmbedCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/questions/': {
      id: '/_authenticated/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof AuthenticatedQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queries/': {
      id: '/_authenticated/queries/'
      path: '/queries'
      fullPath: '/queries/'
      preLoaderRoute: typeof AuthenticatedQueriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs/': {
      id: '/_authenticated/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof AuthenticatedLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data-sources/': {
      id: '/_authenticated/data-sources/'
      path: '/data-sources'
      fullPath: '/data-sources/'
      preLoaderRoute: typeof AuthenticatedDataSourcesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboards/': {
      id: '/_authenticated/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof AuthenticatedDashboardsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/components/': {
      id: '/_authenticated/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof AuthenticatedComponentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collection/': {
      id: '/_authenticated/collection/'
      path: '/collection'
      fullPath: '/collection/'
      preLoaderRoute: typeof AuthenticatedCollectionIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/questions/new': {
      id: '/_authenticated/questions/new'
      path: '/questions/new'
      fullPath: '/questions/new'
      preLoaderRoute: typeof AuthenticatedQuestionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/questions/$id': {
      id: '/_authenticated/questions/$id'
      path: '/questions/$id'
      fullPath: '/questions/$id'
      preLoaderRoute: typeof AuthenticatedQuestionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queries/new': {
      id: '/_authenticated/queries/new'
      path: '/queries/new'
      fullPath: '/queries/new'
      preLoaderRoute: typeof AuthenticatedQueriesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queries/$id': {
      id: '/_authenticated/queries/$id'
      path: '/queries/$id'
      fullPath: '/queries/$id'
      preLoaderRoute: typeof AuthenticatedQueriesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data-sources/new': {
      id: '/_authenticated/data-sources/new'
      path: '/data-sources/new'
      fullPath: '/data-sources/new'
      preLoaderRoute: typeof AuthenticatedDataSourcesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data-sources/$id': {
      id: '/_authenticated/data-sources/$id'
      path: '/data-sources/$id'
      fullPath: '/data-sources/$id'
      preLoaderRoute: typeof AuthenticatedDataSourcesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboards/new': {
      id: '/_authenticated/dashboards/new'
      path: '/dashboards/new'
      fullPath: '/dashboards/new'
      preLoaderRoute: typeof AuthenticatedDashboardsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/components/new': {
      id: '/_authenticated/components/new'
      path: '/components/new'
      fullPath: '/components/new'
      preLoaderRoute: typeof AuthenticatedComponentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/components/$id': {
      id: '/_authenticated/components/$id'
      path: '/components/$id'
      fullPath: '/components/$id'
      preLoaderRoute: typeof AuthenticatedComponentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collection/$folderId': {
      id: '/_authenticated/collection/$folderId'
      path: '/collection/$folderId'
      fullPath: '/collection/$folderId'
      preLoaderRoute: typeof AuthenticatedCollectionFolderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboards/$id/': {
      id: '/_authenticated/dashboards/$id/'
      path: '/dashboards/$id'
      fullPath: '/dashboards/$id/'
      preLoaderRoute: typeof AuthenticatedDashboardsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboards/$id/edit': {
      id: '/_authenticated/dashboards/$id/edit'
      path: '/dashboards/$id/edit'
      fullPath: '/dashboards/$id/edit'
      preLoaderRoute: typeof AuthenticatedDashboardsIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCollectionFolderIdRoute: typeof AuthenticatedCollectionFolderIdRoute
  AuthenticatedComponentsIdRoute: typeof AuthenticatedComponentsIdRoute
  AuthenticatedComponentsNewRoute: typeof AuthenticatedComponentsNewRoute
  AuthenticatedDashboardsNewRoute: typeof AuthenticatedDashboardsNewRoute
  AuthenticatedDataSourcesIdRoute: typeof AuthenticatedDataSourcesIdRoute
  AuthenticatedDataSourcesNewRoute: typeof AuthenticatedDataSourcesNewRoute
  AuthenticatedQueriesIdRoute: typeof AuthenticatedQueriesIdRoute
  AuthenticatedQueriesNewRoute: typeof AuthenticatedQueriesNewRoute
  AuthenticatedQuestionsIdRoute: typeof AuthenticatedQuestionsIdRoute
  AuthenticatedQuestionsNewRoute: typeof AuthenticatedQuestionsNewRoute
  AuthenticatedCollectionIndexRoute: typeof AuthenticatedCollectionIndexRoute
  AuthenticatedComponentsIndexRoute: typeof AuthenticatedComponentsIndexRoute
  AuthenticatedDashboardsIndexRoute: typeof AuthenticatedDashboardsIndexRoute
  AuthenticatedDataSourcesIndexRoute: typeof AuthenticatedDataSourcesIndexRoute
  AuthenticatedLogsIndexRoute: typeof AuthenticatedLogsIndexRoute
  AuthenticatedQueriesIndexRoute: typeof AuthenticatedQueriesIndexRoute
  AuthenticatedQuestionsIndexRoute: typeof AuthenticatedQuestionsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedDashboardsIdEditRoute: typeof AuthenticatedDashboardsIdEditRoute
  AuthenticatedDashboardsIdIndexRoute: typeof AuthenticatedDashboardsIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCollectionFolderIdRoute: AuthenticatedCollectionFolderIdRoute,
  AuthenticatedComponentsIdRoute: AuthenticatedComponentsIdRoute,
  AuthenticatedComponentsNewRoute: AuthenticatedComponentsNewRoute,
  AuthenticatedDashboardsNewRoute: AuthenticatedDashboardsNewRoute,
  AuthenticatedDataSourcesIdRoute: AuthenticatedDataSourcesIdRoute,
  AuthenticatedDataSourcesNewRoute: AuthenticatedDataSourcesNewRoute,
  AuthenticatedQueriesIdRoute: AuthenticatedQueriesIdRoute,
  AuthenticatedQueriesNewRoute: AuthenticatedQueriesNewRoute,
  AuthenticatedQuestionsIdRoute: AuthenticatedQuestionsIdRoute,
  AuthenticatedQuestionsNewRoute: AuthenticatedQuestionsNewRoute,
  AuthenticatedCollectionIndexRoute: AuthenticatedCollectionIndexRoute,
  AuthenticatedComponentsIndexRoute: AuthenticatedComponentsIndexRoute,
  AuthenticatedDashboardsIndexRoute: AuthenticatedDashboardsIndexRoute,
  AuthenticatedDataSourcesIndexRoute: AuthenticatedDataSourcesIndexRoute,
  AuthenticatedLogsIndexRoute: AuthenticatedLogsIndexRoute,
  AuthenticatedQueriesIndexRoute: AuthenticatedQueriesIndexRoute,
  AuthenticatedQuestionsIndexRoute: AuthenticatedQuestionsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedDashboardsIdEditRoute: AuthenticatedDashboardsIdEditRoute,
  AuthenticatedDashboardsIdIndexRoute: AuthenticatedDashboardsIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  EmbedCodeRoute: EmbedCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
